#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

runApplication blockMesh
# runApplication setFields
# runApplication transformPoints -rotate '((0 1 0) (0 0 1))'
runApplication setSolidFraction -subDivisions 4 
runApplication decomposePar
# runApplication laserbeamFoam
NP="${FOAM_RUN_NP:-4}"
runParallel -np "$NP" laserbeamFoam
