#!/bin/bash
## Call as: `./Allrun` to run standard.
## Call as: `./Allrun -p` to run in parallel and use blastAMR if available.

# Handle flags ----------------------------------------------------------------
bParallel=false
bAMR=false
bRichterMode=false # This changes to a 2.5D setup!

print_usage() {
  printf "

Notes for Richter et al. setup:
- Is a 2.5D style case.
- Magnetic field is applied in the z direction.
- z-direction is only 1 cell wide.
- z-normal walls are set to \`zeroGradient\`
- AMR will refine in z direction also, but this should relatively negligble.
- Flow is (should be) predominantly 2D.

Usage: \n\tCall as: \`./Allrun\` to run standard.\
\n\tCall as: \`./Allrun -pa\` to run in parallel and use blastAMR if available.\
\n\tCall as: \`./Allrun -a\` to use blastAMR if available, in serial.\
\n\tCall as: \`./Allrun -p\` for parallel mode only (no AMR).\
\n\Flags   : \`-r\` to enable \'Richter et al.\' setup (2.5D, page normal \
magnetic field).
\n"
}

while getopts 'par' flag; do
  case "${flag}" in
    a) bAMR=true ;;
    p) bParallel=true ;;
    r) bRichterMode=true ;;
    *) print_usage
       exit 1 ;;
  esac
done
# End of Handle flags ---------------------------------------------------------


# Handle 2D vs 2.5D casess
if [ ! -d "initial" ]; then
    mkdir initial
fi

if ${bRichterMode}; then
    echo "Enabled richter mode (2.5D, page normal magnetic field B_z); copying:"
    cp -r --verbose ./initialRichter/* initial
    cp --verbose system/blockMeshDict.richter system/blockMeshDict
else
    echo "Standard mode (2D, horizontal magnetic field B_x); copying:"
    cp -r --verbose ./initial2d/* initial
    cp --verbose system/blockMeshDict.2d system/blockMeshDict
fi


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

# remove `.orig` extensions where applicable
find 0 -name "*.orig" -exec bash -c 'cp "$0" "${0%.orig}"' {} \;

runApplication blockMesh




# If blastAMR in installed, run with AMR
if (command -v updateMesh > /dev/null) && ${bAMR}; then
    echo "blastAMR is available: Note:"
    echo "this uses a hacky workaround to perform initialisation as \
    \`alphaContactAngle\` keyword is unknown to blastAMR's updateMesh."

    cp  constant/dynamicMeshDict.main \
        constant/dynamicMeshDict

    cp  system/controlDict.blastAMR\
        system/controlDict

    # HACK ---- (1/2)
    #> remove the other phase; then let it update the mesh
    rm 0/alpha.GaInSn 0/alpha.GaInSn.orig
    # ---------

    # Below is a copy from blastAMR's dambreak2D
    if [ -z "$AMRLB_PROJECT" ]; then
    echo "AMRLB_PROJECT not set. Please set it to the root of the blastAMR repository."
    echo "For example, for blastAMR tutorials:"
    echo 'export AMRLB_PROJECT=$(git rev-parse --show-toplevel)'
    exit 1
    fi

    echo "blastAMR initial refinement starting"

    export FOAM_CODE_TEMPLATES=$AMRLB_PROJECT/etc/codeTemplates/dynamicCode
    maxRef=$(foamDictionary -entry maxRefinement -value constant/dynamicMeshDict)
    runApplication setFields
    for i in $(seq 1 $maxRef); do
        runApplication -a updateMesh -overwrite
        runApplication -a setFields
    done
    cp -rT 0/polyMesh constant/polyMesh

    # HACK ---- (2/2)
    #> Restore the other phase
    cp initial/alpha.GaInSn.orig 0/alpha.GaInSn
    setFields 2>&1 | tee log.setFields_post
    #> for some reason, runApplication setFields does not
    #  fields update properly.
    # ---------
else
    echo "blastAMR not found in the PATH: skipping"
    mv  constant/dynamicMeshDict \
        constant/dynamicMeshDict.disabled

    cp  system/controlDict.vanilla\
        system/controlDict
fi


runApplication setFields


if ${bParallel}; then
    decomposePar 2>&1 | tee log.decomposePar
    nCores=$(\
        foamDictionary -entry numberOfSubdomains \
                       -value system/decomposeParDict)
    mpirun -np ${nCores} \
        compressibleLaserbeamFoam \
            -parallel \
            2>&1 | tee log.compressibleLaserbeamFoam

    if (command -v updateMesh > /dev/null) && ${bParallel} && ${bAMR}; then
        # This is the fix to reconstruct blastAMR cases
        mpirun -np ${nCores} \
            redistributePar \
                -reconstruct \
                -parallel \
                2>&1 | tee log.redistributePar
    fi
else
    runApplication compressibleLaserbeamFoam
    # compressibleLaserbeamFoam 2>&1 | tee log.compressibleLaserbeamFoam
fi