#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

runApplication blockMesh
runApplication setSolidFraction

# 激光使用极坐标圆斑打在XY顶面，无需旋转网格

# runApplication laserbeamFoam